# https://micronaut-projects.github.io/micronaut-core/latest/guide/configurationreference.html

micronaut:
  application:
    name: micronaut-app
  server:
    port: 8080
  executors:
    # https://docs.micronaut.io/latest/guide/index.html#reactiveServer
    io:
      type: FIXED # default=CACHED
      number-of-threads: 200
  http:
    services:
      exchange-client:
        url: "http://localhost:8888"
        read-timeout: 1m
endpoints:
  all:
    port: 8081

netty:
  default:
    allocator:
      max-order: 3

datasources:
  default:
    maximum-pool-size: 40 # default=10
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/postgres`}
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:postgres}
    driverClassName: ${JDBC_DRIVER:org.postgresql.Driver}
jpa:
  default:
    properties:
      hibernate.hbm2ddl.auto: create-drop
