version: '3.8'
services:
  db:
    image: postgres:14.4
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'

  wiremock:
    image: wiremock/wiremock:2.32.0
    ports:
      - "8888:8080"
    command:
      - "--global-response-templating"
    volumes:
      - ./common-wiremock/src/main/resources/stubs:/home/wiremock
