version: "3.8"
services:
  db:
    container_name: db
    image: postgres:14.4
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  wiremock:
    container_name: wiremock
    image: wiremock/wiremock:2.35.0
    ports:
      - "8888:8080"
    command: [ "--async-response-enabled=true", "--no-request-journal" ]
    volumes:
      - ./common-wiremock/src/main/resources/stubs:/home/wiremock
