server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

database:
  driverClass: org.postgresql.Driver
  user: postgres
  password: postgres
  url: jdbc:postgresql://localhost:5432/postgres?loggerLevel=OFF
  properties:
    hibernate.dialect: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate.hbm2ddl.auto: create-drop
    #hibernate.show_sql: true
    #hibernate.hbm2ddl.import_files:

exchangeClientConfig:
  basePath: 'http://localhost:8888/exchanges?currency='

logging:
  level: INFO
  loggers:
    bitxon.dropwizard: DEBUG
    org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: ERROR
