# https://www.dropwizard.io/en/latest/manual/configuration.html

server:
  maxThreads: 200 # default=1024
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
  requestLog:
    appenders: [] # Disable default logging (response status)

database:
  maxSize: 40 # default=100
  driverClass: org.postgresql.Driver
  user: postgres
  password: postgres
  url: jdbc:postgresql://localhost:5432/postgres?loggerLevel=OFF
  properties:
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.hbm2ddl.auto: create-drop
    #hibernate.show_sql: true
    #hibernate.hbm2ddl.import_files:

exchangeClientConfig:
  basePath: 'http://localhost:8888/exchanges?currency='
  timeout: 5s # default=0.5s

logging:
  level: INFO
  loggers:
    bitxon.dropwizard: DEBUG
    org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: ERROR
