server:
  port: 8080
management:
  server:
    port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  jpa.hibernate.ddl-auto: create-drop
  #jpa.show-sql: true

http:
  exchange-client:
    url: http://localhost:8888

logging:
  level:
    root: INFO
    bitxon.dropwizard: DEBUG
    org.springframework.web.servlet.mvc.support.DefaultHandlerExceptionResolver: ERROR
